# Generated by Django 2.2.1 on 2019-06-04 00:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('group', models.CharField(choices=[('CLEANING', 'Cleaning'), ('DRINK', 'Drink'), ('FOOD', 'Food'), ('TOILETRIES', 'Toiletries')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(choices=[('box', 'box'), ('bottle', 'bottle'), ('case', 'case'), ('dozen', 'dozen'), ('gallon', 'gallon'), ('halfdozen', 'half-dozen'), ('halfgallon', 'half-gallon'), ('roll', 'roll'), ('sixpack', 'six pack')], max_length=500)),
                ('date_purchased', models.DateField()),
                ('date_expires', models.DateField(blank=True, null=True)),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('date_delta', models.IntegerField(blank=True, help_text='Difference in days between purchase and usage/expiration', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_finished', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
