# Generated by Django 2.2.1 on 2019-06-02 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField(default=0.0, validators=[django.core.validators.MinLengthValidator(0.0), django.core.validators.MaxLengthValidator(1000.0)])),
                ('quantity', models.FloatField(default=1.0)),
                ('unit', models.CharField(choices=[('box', 'box'), ('case', 'case'), ('dozen', 'dozen'), ('gallon', 'gallon'), ('halfgallon', 'half-gallon'), ('roll', 'roll'), ('sixpack', 'six pack')], max_length=1)),
                ('category', models.CharField(choices=[('Cleaning', (('c_bath', 'bathroom'), ('c_kitchen', 'kitchen'), ('c_laundry', 'laundry'), ('c_surfaces', 'surface'), ('c_other', 'other cleaner'))), ('Drink', (('d_soft', 'soft drink'), ('d_alcohol', 'alcohol'), ('d_other', 'other drink'))), ('Food', (('f_cereal', 'cereal'), ('f_condiment', 'condiment'), ('f_dairy', 'dairy'), ('f_fish', 'fish'), ('f_meat', 'meat'), ('f_snack', 'snack'), ('f_spice', 'spice'), ('f_other', 'other food'))), ('Toiletries', (('t_bodywash', 'body wash'), ('t_dental', 'dental'), ('t_hairstyle', 'hair styling'), ('t_hairwash', 'hair wash'), ('t_tissue', 'tissues'), ('t_other', 'other toiletry')))], max_length=1)),
                ('date_purchased', models.DateField()),
                ('date_finished', models.DateField()),
                ('date_delta', models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0)])),
            ],
        ),
    ]
