# Generated by Django 2.2.1 on 2019-06-03 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190602_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_expires',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cleaning', (('c_bath', 'bathroom'), ('c_kitchen', 'kitchen'), ('c_laundry', 'laundry'), ('c_surfaces', 'surface'), ('c_other', 'other cleaner'))), ('Drink', (('d_beer', 'beer'), ('d_dairy', 'dairy'), ('d_juice', 'juice'), ('d_liquer', 'liquer'), ('d_liquor', 'liquor'), ('d_pop', 'soda pop'), ('d_soft', 'soft drink'), ('d_other', 'other drink'))), ('Food', (('f_cereal', 'cereal'), ('f_condiment', 'condiment'), ('f_dairy', 'dairy'), ('f_fish', 'fish'), ('f_meat', 'meat'), ('f_snack', 'snack'), ('f_spice', 'spice'), ('f_other', 'other food'))), ('Toiletries', (('t_bodywash', 'body wash'), ('t_dental', 'dental'), ('t_hairstyle', 'hair styling'), ('t_hairwash', 'hair wash'), ('t_tissue', 'tissues'), ('t_other', 'other toiletry')))], max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_delta',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_finished',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('box', 'box'), ('case', 'case'), ('dozen', 'dozen'), ('gallon', 'gallon'), ('halfgallon', 'half-gallon'), ('roll', 'roll'), ('sixpack', 'six pack')], max_length=500),
        ),
    ]
