# Generated by Django 2.2.1 on 2019-06-03 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190603_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_delta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
    ]
