# Generated by Django 2.2.1 on 2019-06-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190603_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('box', 'box'), ('bottle', 'bottle'), ('case', 'case'), ('dozen', 'dozen'), ('gallon', 'gallon'), ('halfdozen', 'half-dozen'), ('halfgallon', 'half-gallon'), ('roll', 'roll'), ('sixpack', 'six pack')], max_length=500),
        ),
    ]
