# Generated by Django 2.2.1 on 2019-06-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190603_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cleaning', (('c_bath', 'bathroom'), ('c_kitchen', 'kitchen'), ('c_laundry', 'laundry'), ('c_surfaces', 'surface'), ('c_other', 'other cleaner'))), ('Drink', (('d_beer', 'beer'), ('d_dairy', 'dairy'), ('d_juice', 'juice'), ('d_liquer', 'liquer'), ('d_liquor', 'liquor'), ('d_pop', 'soda pop'), ('d_soft', 'soft drink'), ('d_other', 'other drink'))), ('Food', (('f_cereal', 'cereal'), ('f_condiment', 'condiment'), ('f_dairy', 'dairy'), ('f_fish', 'fish'), ('f_meat', 'meat'), ('f_snack', 'snack'), ('f_spice', 'spice'), ('f_other', 'other food'))), ('Toiletries', (('t_bandages', 'bandages'), ('t_bodywash', 'body wash'), ('t_dental', 'dental'), ('t_hairstyle', 'hair styling'), ('t_hairwash', 'hair wash'), ('t_medicine', 'medicine'), ('t_tissue', 'tissues'), ('t_other', 'other toiletry')))], max_length=500),
        ),
    ]
