# Generated by Django 2.2.1 on 2019-06-03 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190603_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_delta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Difference in days between purchase and usage/expiration'),
        ),
    ]
