# Generated by Django 2.2.1 on 2019-06-03 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190603_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_delta',
            field=models.IntegerField(blank=True, help_text='Difference in days between purchase and usage/expiration', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
