# Generated by Django 2.2.1 on 2019-06-03 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190603_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('category_group', models.CharField(choices=[('CLEANING', 'Cleaning'), ('DRINK', 'Drink'), ('FOOD', 'Food'), ('TOILETRIES', 'Toiletries')], max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
