# Generated by Django 2.2.1 on 2019-06-04 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190603_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
